# Generated by Django 5.2.6 on 2025-10-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_vendorprofile_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_images/'),
        ),
    ]
