# Generated by Django 5.2.6 on 2025-11-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pickup_address',
            field=models.TextField(blank=True, help_text='Street Address / Landmark', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
