# Generated by Django 5.2.6 on 2025-11-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_loyaltyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyprofile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loyaltyprofile',
            name='rank',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')], default='Bronze', max_length=10),
        ),
    ]
