# Generated by Django 5.2.6 on 2025-11-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_loyaltyprofile_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('Domestic', 'Domestic'), ('Overseas', 'Overseas'), ('Metro Manila', 'Metro Manila'), ('North Luzon', 'North Luzon'), ('South Luzon', 'South Luzon'), ('Visayas', 'Visayas'), ('Mindanao', 'Mindanao')], default='Visayas', max_length=50, null=True),
        ),
    ]
