# Generated by Django 5.2.6 on 2025-12-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('Cebu City', 'Cebu City'), ('Mandaue City', 'Mandaue City'), ('Lapu-Lapu City', 'Lapu-Lapu City'), ('Talisay City', 'Talisay City'), ('Minglanilla', 'Minglanilla'), ('Consolacion', 'Consolacion'), ('Compostela', 'Compostela'), ('Liloan', 'Liloan'), ('Naga City', 'Naga City'), ('Carcar City', 'Carcar City'), ('Toledo City', 'Toledo City'), ('Danao City', 'Danao City'), ('Bogo City', 'Bogo City')], default='Cebu City', max_length=50, null=True),
        ),
    ]
