# Generated by Django 5.2.6 on 2025-11-02 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_moderator_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason given by the user for reporting the message.')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('moderation_action', models.CharField(choices=[('none', 'No Action Taken'), ('warn', 'Warn User'), ('delete', 'Delete Message'), ('ban', 'Ban User')], default='none', help_text='The final action taken by the admin.', max_length=50)),
                ('resolution_notes', models.TextField(blank=True, help_text='Internal notes on the resolution.', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='messaging.message')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Report',
                'verbose_name_plural': 'Message Reports',
                'unique_together': {('message', 'reporter')},
            },
        ),
    ]
