# Generated by Django 5.2.6 on 2025-12-02 06:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Fresh Produce', 'Fresh Produce'), ('Grains and Staples', 'Grains and Staples'), ('Packaged Goods', 'Packaged Goods'), ('Dairy & Eggs', 'Dairy & Eggs'), ('Meat, Poultry and Seafood', 'Meat, Poultry and Seafood'), ('Local & Specialty Products', 'Local & Specialty Products'), ('Services', 'Services')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
