# Generated by Django 5.2.6 on 2025-12-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_seasonal',
            field=models.BooleanField(default=False, help_text='Mark if this product is currently in season'),
        ),
    ]
