# Generated by Django 5.2.6 on 2025-12-02 17:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_seasonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Fresh Produce', 'Fresh Produce'), ('Grains & Staples', 'Grains & Staples'), ('Packaged Goods', 'Packaged Goods'), ('Dairy & Eggs', 'Dairy & Eggs'), ('Meat, Poultry & Seafood', 'Meat, Poultry & Seafood'), ('Local & Specialty Products', 'Local & Specialty Products'), ('Services', 'Services')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
